//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airplanes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public int Id { get; set; }
        public int OwnedById { get; set; }
        public Nullable<int> CurrentAirportId { get; set; }
        public Nullable<int> NextDestinationId { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
    }
}
